Initial commit
valitydev/openapi-transfer pull request #2
Opened 2024-05-07 13:36 UTC by vitaxa

2024-05-08 11:06 UTC, strug commented on openapi/components/schemas/PersonalData/NonResidentSenderPersonalData.yaml
> +  migrationCard:
точно не обязательное?

2024-05-08 11:06 UTC, strug commented on openapi/components/schemas/PersonalData/PersonName.yaml
> +type: object
меня как-то эта структура смущает, по крайней мере когда будет name.name, может хотя бы само поле переименовать в personName, а то как то в имени лежит фамилия не очевидно. Ну либо вообще развернуть ее мерджем, если хочется переиспользовать

2024-05-08 11:06 UTC, strug commented on openapi/components/schemas/PersonalData/ReceiverPersonalData.yaml
> +  birthPlace:
а дата рождения не нужна?

2024-05-08 11:06 UTC, strug commented on openapi/components/schemas/Transfer/TransferConfirm.yaml
> +  conversionRate:
что будет если я подменю курс при подтверждении, не должны ли мы его хранить у себя и тогда тут его не ждать?

2024-05-08 11:24 UTC, vitaxa commented on openapi/components/schemas/Transfer/TransferFixRate.yaml
> +  receiverCardNumber:
Да, кладем в CDS, также как и в случае с персональными данными, будем класть их в отдельное хранилище и работать с токеном

2024-05-08 11:27 UTC, vitaxa commented on openapi/components/schemas/PersonalData/NonResidentSenderPersonalData.yaml
> +  migrationCard:
Судя из требований - не обязательное
<img width="1095" alt="image" src="https://github.com/valitydev/openapi-transfer/assets/1349255/3044ad2e-7f90-47a0-abb5-879d15cce809">

2024-05-08 12:40 UTC, vitaxa commented on openapi/components/schemas/Transfer/TransferConfirm.yaml
> +  conversionRate:
Это тот самый курс xfer, обсуждали с бизнесом, предполагается что этот курс будут отправлять не в момент фиксации курса на стороне банка-эквайера выплат, а именно когда пользователь согласился на перевод и xfer передает нам курс по которому они сконвертируют валюту.

2024-05-08 12:45 UTC, vitaxa commented on openapi/components/schemas/PersonalData/ReceiverPersonalData.yaml
> +  birthPlace:
Даже не так, тут должна быть дата рождения вместо места рождения. Поправил

2024-05-08 12:46 UTC, vitaxa commented on openapi/components/schemas/PersonalData/PersonName.yaml
> +type: object
Потыкался с merge, текущий скрипт merge не отрабатывает, надо писать новый под это дело. Старый от swagger так легко не взлетает, его тоже надо переписывать под новый oss3 и redocly. Короче просто отказался от отдельного PersonName

2024-05-08 12:47 UTC, vitaxa commented on openapi/components/schemas/Transfer/TransferFixRate.yaml
> +    $ref: ./TransferCashAmount.yaml
Угу, переделал

2024-05-13 15:06 UTC, WWWcool commented on openapi/components/schemas/Transfer/TransferConfirm.yaml
> +  conversionRate:
тоже не понял зачем этот курс, ощущение что значение курса это результат предыдущего запроса

2024-05-13 15:14 UTC, WWWcool commented on openapi/components/schemas/Transfer/TransferConfirm.yaml
> +  conversionRate:
прочитал док - вопрос отпал - как понял - этот курс - это интерес банка - возможно стоит как то это написать понятнее

2024-05-13 15:16 UTC, WWWcool commented
я бы предложил сразу расширить апишку разделом про пользователей - то есть выделить их в отдельные структуры данных и сохранять получать отдельно, чтобы не делать это каждый раз и дать возможность например быстрее повторять операции. ТОже самое с карточными данными

2024-05-13 15:22 UTC, WWWcool commented on openapi/components/schemas/Transfer/TransferConfirm.yaml
> +  conversionRate:
<img width="712" alt="Снимок экрана 2024-05-13 в 18 21 13" src="https://github.com/valitydev/openapi-transfer/assets/8044981/f66c2875-0a32-49f8-898b-989e1839ad65">
это вопрос к финансам как я понимаю - если мы хотим мержить два курса то это отдельная задача расчета, особенно учитывая, что расчетов такого типа у нас нет - как мне это видится - это калькулирование, результатом которого является наш кешфлоу

2024-05-14 10:11 UTC, tolkonepiu requested changes

2024-05-14 10:11 UTC, tolkonepiu commented on openapi/components/schemas/Transfer/TransferConversionRate.yaml
> +
Лишние отступы

2024-05-14 10:11 UTC, tolkonepiu commented on openapi/components/schemas/PersonalData/NonResidentSenderPersonalData.yaml
> +    $ref: ./PersonIdentification.yaml
А тут у нас идентичный набор для резидента и нерезидента? Не хотим сделать дискриминатором?

2024-05-14 10:11 UTC, tolkonepiu commented on openapi/components/schemas/Transfer/TransferConfirm.yaml
> +  sender:
Мы именно на конфирме хотим запрашивать данные? Кажется, что это долгий этап для плательщика, а у нас еще и фиксация курса в промежутке.

2024-05-14 11:25 UTC, vitaxa commented on openapi/components/schemas/PersonalData/NonResidentSenderPersonalData.yaml
> +    $ref: ./PersonIdentification.yaml
Паспортные данные идентичны, а вот разница выражена в разделении на NonResidentSenderPersonalData и ResidentSenderPersonalData.

2024-05-14 12:13 UTC, vitaxa commented on openapi/components/schemas/Transfer/TransferConfirm.yaml
> +  sender:
Да, хорошее замечание, я предполагал, что пользователь предварительно заполнил эти данные перед фиксированием курса. Тогда сделаю более явно, так чтобы персональные данные передавались в том числе на этапе фиксации курса, по сути предварительная инициализация платежа. Тогда второй endpoint будет просто подтверждением о намерении перевода. Именно на подтверждении перевода мы будем делать тяжелые операции, вроде проверок на ПоискПРО.

2024-05-14 12:42 UTC, vitaxa commented
> я бы предложил сразу расширить апишку разделом про пользователей - то есть выделить их в отдельные структуры данных и сохранять получать отдельно, чтобы не делать это каждый раз и дать возможность например быстрее повторять операции. ТОже самое с карточными данными

В этом есть смысл, в рамках party сохранять персональные и карточные данные. Это немного усложнит клиент, но нашу часть сделает проще и гибче.

2024-05-14 17:25 UTC, tolkonepiu commented on openapi/components/schemas/PersonalData/NonResidentSenderPersonalData.yaml
> +    $ref: ./PersonIdentification.yaml
👌

2024-05-15 09:20 UTC, tolkonepiu commented
@vitaxa давайте наверное вмерджимся, а последующие правки уже в новом pr. Базово мне все ок по api.

2024-05-15 09:20 UTC, tolkonepiu approved these changes

2024-05-15 13:33 UTC, vitaxa commented on openapi/components/schemas/Transfer/TransferConfirm.yaml
> +  conversionRate:
Подробнее от бизнеса это вопрос мы еще проработаем, пока условно добавил курс на апишку, детали еще распишем (в том числе в API)

2024-05-15 13:33 UTC, merged